#!/usr/bin/env bash

# Check if correct number of arguments provided
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
path_to_file="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username"@"$server_ip":~/ 

# Check if scp command succeeded
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Error transferring file"
fi
