#!/usr/bin/env bash
# This script configures a brand new Ubuntu machine to add a custom HTTP response header to Nginx

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure custom HTTP response header
sudo sed -i '/server_name localhost;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
