#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format
# Display header
# Display process information using ps command
# Show process hierarchy

ps -a -x -u -f
