#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format

# Display header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Display process information using ps command
ps aux --forest | awk '{printf "%-10s %5s %4s %4s %6s %6s %-8s %-4s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' | head -50
