#!/usr/bin/env bash
# This script stops the 7-highlander process

# Find the PID of the 7-highlander process
pid=$(pgrep -f '7-highlander')

# Check if the process is running
if [ -n "$pid" ]; then
    # Terminate the process
    echo "Terminating 7-highlander process..."
    pkill -f '7-highlander'
else
    echo "The 7-highlander process is not running."
fi

