#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# With a sleep of 2 in between each iteration
# Responds to SIGTERM signal with "I am invincible!!!"
# Function to handle SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done

