#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data

# Using awk to count occurrences and display data
awk '{ count[$1" "$9]++ } END { for (key in count) print count[key], key }' apache-access.log | sort -nr

