#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using a while loop

# Initializing a counter
counter=0

# Using a while loop to display "Best School" until the counter reaches 10
while [ $counter -lt 10 ]; do
    echo "Best School"
    ((counter++))
done
