#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using an until loop

# Initializing a counter
counter=0

# Using an until loop to display "Best School" until the counter reaches 10
until [ $counter -eq 10 ]; do
    echo "Best School"
    ((counter++))
done

