#!/usr/bin/env bash
# This script loops from 1 to 10 and displays messages based on loop iteration

# Initializing a counter
counter=1

# Using a while loop to iterate from 1 to 10
while [ $counter -le 10 ]; do
    # Using if, elif, and else statements to display messages based on loop iteration
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    # Incrementing the counter
    ((counter++))
done

