#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Use ifconfig to display IPv4 addresses
ifconfig | grep -oP 'inet (addr:)?\K([0-9]{1,3}\.){3}[0-9]{1,3}' | awk '{print $1}'

